### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by briteming** [xutianyi1999/rs-proxy#1]
hi.

yudeMacBook-Air:rs-proxy ym$ cargo build --release
显示：
...
Compiling log4rs v1.0.0
   Compiling tokio v1.17.0
    Building [=======================>  ] 97/102: serde_yaml, regex, tokio,...
    Building [========================> ] 99/102: tokio, log4rs               

   Compiling rs-proxy v0.1.0 (/Users/ym/rs-proxy)
error[E0425]: cannot find value `lib_name` in this scope
   --> src/client/mod.rs:103:40
    |
103 |     let lib = libloading::Library::new(lib_name).res_auto_convert()?;
    |                                        ^^^^^^^^ not found in this scope

error[E0425]: cannot find function `set_keepalive` in this scope
  --> src/commons/mod.rs:78:5
   |
78 |     set_keepalive(self)
   |     ^^^^^^^^^^^^^ help: you might have meant to call the method: `self.set_keepalive`

error[E0425]: cannot find function `set_keepalive` in this scope
  --> src/commons/mod.rs:84:5
   |
84 |     set_keepalive(self)
   |     ^^^^^^^^^^^^^ help: you might have meant to call the method: `self.set_keepalive`

warning: unused import: `Socket`
 --> src/commons/mod.rs:4:15
  |
4 | use socket2::{Socket, TcpKeepalive};
  |               ^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

For more information about this error, try `rustc --explain E0425`.
warning: `rs-proxy` (bin "rs-proxy") generated 1 warning
error: could not compile `rs-proxy` due to 3 previous errors; 1 warning emitted
yudeMacBook-Air:rs-proxy ym$

怎么解决？
谢谢

**Comment by xutianyi1999** [comment]
目前这个库目前已放弃维护，如果是找rust实现的socks5协议可以考虑参考 https://github.com/xutianyi1999/mutsuki 这个库，如果是找梯子请选择更成熟的方案
